services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: .env  # Corrected

  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5174:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  auth:
    restart: unless-stopped
    build: ./auth
    volumes:
      - ./auth:/auth
    ports:
      - 5175:5175
    depends_on:
      - postgres
    env_file: .env  # Corrected

  report:
    restart: unless-stopped
    build: ./report
    volumes:
      - ./report:/report
    ports:
      - 5176:5176
    depends_on:
      - postgres
    env_file: .env  # Corrected

  notification:
    restart: unless-stopped
    build: ./notification
    volumes:
      - ./notification:/notification
    ports:
      - 5177:5177
    depends_on:
      - postgres
    env_file: .env  # Corrected

  follow:
    restart: unless-stopped
    build: ./follow
    volumes:
      - ./follow:/follow
    ports:
      - 5178:5178
    depends_on:
      - postgres
      - report
    env_file: .env  # Corrected

volumes:
  pgdata: {}
  pgadmin: {}
