services:
  frontend:
    build: ./frontend
    ports:
    - "5173:5173"

  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5174:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  auth:
    restart: unless-stopped
    build: ./auth
    volumes:
      - ./auth:/auth
    ports:
      - 5175:5175
    depends_on:
      - postgres
    env_file:
      - path: .env

  report:
    restart: unless-stopped
    build: ./report
    volumes:
      - ./report:/report
    ports:
      - 5176:5176
    depends_on:
      - postgres
    env_file:
      - path: .env

volumes:
  pgdata: {}
  pgadmin: {}